name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      run: |
        brew install qt@6
        echo "Qt6_DIR=$(brew --prefix qt@6)/lib/cmake/Qt6" >> $GITHUB_ENV

    - name: Install libssh
      run: brew install libssh

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix qt@6) -DENABLE_TESTING=OFF

    - name: Build
      run: |
        cd build
        make -j4 ssh-client

    - name: Create DMG
      run: |
        cd build
        macdeployqt ssh-client.app -dmg
        mv ssh-client.dmg ssh-client-macos.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ssh-client-macos
        path: build/ssh-client-macos.dmg

  release:
    needs: [build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ssh-client-macos/ssh-client-macos.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
